version: '3'

services:
  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: "concourse"
      POSTGRES_PASSWORD: "changeme"
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    links: [concourse-db]
    command: web
    expose: ["8080"]
    depends_on: [concourse-db]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      VIRTUAL_HOST: concourse.sanaudon.com
      CONCOURSE_BASIC_AUTH_USERNAME: "concourse"
      CONCOURSE_BASIC_AUTH_PASSWORD: "changeme"
      CONCOURSE_EXTERNAL_URL: "http://concourse.sanaudon.com"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: "concourse"
      CONCOURSE_POSTGRES_PASSWORD: "changeme"
      CONCOURSE_POSTGRES_DATABASE: concourse
  
  concourse-worker:
    image: concourse/concourse
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web

  minio:
    image: minio/minio
    volumes: ["./minio-data:/export"]
    environment:
      VIRTUAL_HOST: minio.sanaudon.com
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    command: server /export

  httpd:
    image: httpd:2.4
    volumes: ["./minio-data:/usr/local/apache2/htdocs"]
    environment:
      VIRTUAL_HOST: apache.sanaudon.com

networks:
  default:
    external:
      name: shared


