version: '3'

services:
  gitbucket:
    image: takezoe/gitbucket
    expose: ["8080"]
    environment:
      VIRTUAL_HOST: gitbucket.sanaudon.com
      VIRTUAL_PORT: 8080
networks:
  default:
    external:
      name: shared

